DAILY_LIFE/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAILY_LIFE.Models;

namespace DAILY_LIFE.Controllers
{
    public class UserController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: User
        public ActionResult Index()
        {
            return View(db.tbl_user.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user tbl_user = db.tbl_user.Find(id);
            if (tbl_user == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user_id,user_code,user_username,user_password,user_firstname,user_lastname")] tbl_user tbl_user)
        {
            if (ModelState.IsValid)
            {
                db.tbl_user.Add(tbl_user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user tbl_user = db.tbl_user.Find(id);
            if (tbl_user == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_id,user_code,user_username,user_password,user_firstname,user_lastname")] tbl_user tbl_user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_user);
        }

        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user tbl_user = db.tbl_user.Find(id);
            if (tbl_user == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_user tbl_user = db.tbl_user.Find(id);
            db.tbl_user.Remove(tbl_user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DAILY_LIFE/Controllers/UserTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAILY_LIFE.Models;

namespace DAILY_LIFE.Controllers
{
    public class UserTypeController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        // GET: UserType
        public ActionResult Index()
        {
            return View(db.tbl_user_type.ToList());
        }

        // GET: UserType/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user_type tbl_user_type = db.tbl_user_type.Find(id);
            if (tbl_user_type == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user_type);
        }

        // GET: UserType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserType/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user_type_id,user_type_name")] tbl_user_type tbl_user_type)
        {
            if (ModelState.IsValid)
            {
                db.tbl_user_type.Add(tbl_user_type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_user_type);
        }

        // GET: UserType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user_type tbl_user_type = db.tbl_user_type.Find(id);
            if (tbl_user_type == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user_type);
        }

        // POST: UserType/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "user_type_id,user_type_name")] tbl_user_type tbl_user_type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_user_type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_user_type);
        }

        // GET: UserType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_user_type tbl_user_type = db.tbl_user_type.Find(id);
            if (tbl_user_type == null)
            {
                return HttpNotFound();
            }
            return View(tbl_user_type);
        }

        // POST: UserType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_user_type tbl_user_type = db.tbl_user_type.Find(id);
            db.tbl_user_type.Remove(tbl_user_type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DAILY_LIFE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DEILY LIFE CORPORATION</title>


    <link href="~/Content/style.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/simple-sidebar.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">



    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>



<body>

    <div id="wrapper" class="toggled">

        <div class="row header">
            <div class="col-2">
                <a onclick="menu_toggle()" class="btn" style="cursor: pointer;">
                    <div class="menu-icon"></div>
                    <div class="menu-icon"></div>
                    <div class="menu-icon"></div>
                </a>
            </div>
            <div class="col-10" align="right">
                <div class="dropdown" style="cursor: pointer;">
                    <img src="~/img/default.png" class="avatar" />
                    <button class="dropbtn">
                        นายวรายุทธ เทกระโทก
                        <i class="fa fa-caret-down"></i>
                    </button>

                    <div class="dropdown-content">
                        <a class="dropdown-item" href="@Url.Action("Index", "User")"><i class="fa fa-user"></i>Profile</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "UserType")"><i class="fa fa-sign-out"></i>Log Out</a>
                    </div>

                </div>
            </div>
        </div>

        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">


                <li class="logo">
                    <div align="center">
                        <a href="@Url.Action("Index", "User")">
                            <img src="~/img/placeholder.jpg" class="img-responsive" style=" padding-top: 10%" width="170px">
                        </a>
                    </div>
                </li>
                <li>
                    <div style="padding: 20px 0; text-indent: 0px;" align="center">
                        <span class="brand-line-one"></span><br>
                        <a href="@Url.Action("Index", "User")">
                            <span class="brand-line-second"> DAILY LIFE CORPORATION</span><br>
                        </a>
                    </div>
                </li>

                <li>
                    <a href="@Url.Action("Index", "UserType")">
                        <div>
                            <i class="fab fa-typo3" style="font-size:24px"></i>
                            <span style="padding:5px; font-size:15px; "> ประเภทผู้ใช้งาน </span>
                        </div>
                    </a>
                </li>

                <li>
                    <a href="@Url.Action("Index", "User")">
                        <div>
                            <i class="fas fa-user" style="font-size:24px"></i>
                            <span style="padding:5px; font-size:15px;"> ผู้ใช้งาน </span>
                        </div>
                    </a>
                </li>


            </ul>
        </div>


        <div id="page-content-wrapper">
            @RenderBody()
        </div>

        <center>
            <footer>
                <p>&copy; @DateTime.Now.Year - DEILY LIFE CORPORATION</p>
            </footer>
        </center>
        <script>
            function menu_toggle() {
                $("#wrapper").toggleClass("toggled");
            }
        </script>


</body>

</html>